framework:
    messenger:
        # Keep this for other message types if needed
        transports:
            sync: 'sync://'  # Synchronous transport for immediate message processing

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []  # Default bus configuration

        routing:
            # You can remove this part since you're not using Messenger for sending emails
            # Symfony\Component\Mailer\Messenger\SendEmailMessage: brevo  # Route email messages to brevo transport (Remove this line)
            # Remove SMS routing if you don't need it
            # Symfony\Component\Notifier\Message\SmsMessage: sync  # This line is removed or commented out if SMS is not needed
