# config/packages/reset_password.yaml
symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 3600 # 1 heure en secondes
    throttle_limit: 3600 # 1 heure entre chaque tentative
    enable_garbage_collection: true