security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\Utilisateur:
            algorithm: bcrypt
            cost: 12
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppAuthenticator
            entry_point: App\Security\AppAuthenticator
            form_login:
                enable_csrf: true
                csrf_token_id: authenticate
                csrf_parameter: _csrf_token
                username_parameter: login_form[email]
                password_parameter: login_form[mot_de_passe]
            logout:
                path: app_logout
                target: app_login
                invalidate_session: true
                delete_cookies:
                    - REMEMBERME
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                secure: false
                httponly: true
                samesite: lax

    access_control:
         - { path: ^/landing, roles: PUBLIC_ACCESS }
         - { path: ^/events, roles: PUBLIC_ACCESS }
         - { path: ^/choose-role, roles: PUBLIC_ACCESS }
         - { path: ^/shops, roles: PUBLIC_ACCESS }
         - { path: ^/login, roles: PUBLIC_ACCESS }
         - { path: ^/signup/shop-owner, roles: PUBLIC_ACCESS }
         - { path: ^/signup/User, roles: PUBLIC_ACCESS }
         - { path: ^/home, roles: ROLE_CLIENT }
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/shopOwner, roles: ROLE_SHOPOWNER }
         - { path: ^/client, roles: ROLE_CLIENT }
         - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon