# config/packages/security.yaml
security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\Utilisateur:
            algorithm: bcrypt
            cost: 12

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppAuthenticator
            entry_point: App\Security\AppAuthenticator
            form_login:
                enable_csrf: true
                csrf_token_id: authenticate
                csrf_parameter: _csrf_token
                username_parameter: login_form[email]
                password_parameter: login_form[mot_de_passe]
            logout:
                path: app_logout
                target: app_login
                invalidate_session: true
                delete_cookies:
                    - REMEMBERME
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                secure: false
                httponly: true
                samesite: lax

    access_control:
    - { path: ^/admin/dashboard1, roles: PUBLIC_ACCESS }
    - { path: ^/atms, roles: PUBLIC_ACCESS }
    - { path: ^/shopsadmin, roles: PUBLIC_ACCESS }
    - { path: ^/parking, roles: PUBLIC_ACCESS }
    - { path: ^/eventsadmin, roles: PUBLIC_ACCESS }
    - { path: ^/usersgestion, roles: PUBLIC_ACCESS } 
    - { path: ^/commande, roles: PUBLIC_ACCESS }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/shopowner, roles: ROLE_SHOPOWNER }
    - { path: ^/client, roles: ROLE_CLIENT }
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/signup/shop-owner, roles: PUBLIC_ACCESS }
    - { path: ^/signup/User, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }