vich_uploader:
    db_driver: orm

    mappings:
        reservation_image:
            uri_prefix: /uploads/images/reservations
            upload_destination: '%kernel.project_dir%/public/uploads/images/reservations'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true