# config/services.yaml
parameters:

    products_directory: '%kernel.project_dir%/public/uploads/products'

services:
    # Configuration par défaut pour tous les services
    _defaults:
        autowire: true      # Active l'injection automatique des dépendances
        autoconfigure: true # Active la configuration automatique des tags
        public: false       # Rend les services privés par défaut                                                   
    

     #App\Entity\User:
    #     class: App\Entity\User
    #     autowire: true            
    App\EventListener\NoCacheListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }  
    # Charge automatiquement tous les services du dossier src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # Configuration explicite pour l'Authenticator
    App\Security\AppAuthenticator:
        public: true
        tags: ['security.authenticator']
        arguments:
            $urlGenerator: '@router.default'
            $userRepository: '@App\Repository\UtilisateurRepository'
            

    # Configuration pour les contrôleurs
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
        public: true

# Configuration spécifique pour l'environnement de développement
when@dev:
    services:
        # Désactive certains services du profiler en production
        Symfony\Bundle\WebProfilerBundle\DataCollector\TemplateAwareDataCollectorInterface:
            public: false

# Configuration spécifique pour les tests
when@test:
    services:
        # Crée une version de test de l'Authenticator
        test.App\Security\AppAuthenticator:
            parent: 'App\Security\AppAuthenticator'
            public: true
#          
